### ISSUE TITLE
preserve static IP field not working

### ISSUE THREAD

**Issue by jsakil14** [kubev2v/forklift#1113]
When I migrate from vmware to kubevirt using forklift , the preserve static IP filed when selected doesnt apply and defaults to Use System default setting. How do we enforce this ? I am using : latest images - let me know what logs are needed. Due to this , guest OS doesnt have the IP config preserved.

**Comment by jsakil14** [comment]
@mnecas Is this relevant for the virt-io drivers for windows issue which was resolved yesterday?

**Comment by jsakil14** [comment]
https://github.com/kubev2v/forklift-console-plugin/issues/1133#issuecomment-2421946040

**Comment by jsakil14** [comment]
Am trying to add this , but it just doesnt allow me.

k apply -f /var/folders/7g/kjjlhgyn65d_zw5zb8f6c_6c0000gp/T/kubectl-edit-894711451.yaml
error: error validating "/var/folders/7g/kjjlhgyn65d_zw5zb8f6c_6c0000gp/T/kubectl-edit-894711451.yaml": error validating data: ValidationError(Plan.spec): unknown field "preserveStaticIPs" in io.konveyor.forklift.v1beta1.Plan.spec; if you choose to ignore these errors, turn validation off with --validate=false
% cat /var/folders/7g/kjjlhgyn65d_zw5zb8f6c_6c0000gp/T/kubectl-edit-894711451.yaml

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# plans.forklift.konveyor.io "copy-of-windows" was not valid:
# * <nil>: Invalid value: "The edited file failed validation": ValidationError(Plan.spec): unknown field "preserveStaticIPs" in io.konveyor.forklift.v1beta1.Plan.spec
#
apiVersion: forklift.konveyor.io/v1beta1
kind: Plan
metadata:
  annotations:
    populatorLabels: "True"
  creationTimestamp: "2024-10-18T09:02:46Z"
  generation: 2
  name: copy-of-windows
  namespace: konveyor-forklift
  resourceVersion: "617907626"
  uid: 5d79ebd5-3bd4-4cd7-ab3b-81f00361c354
spec:
  archived: false
  map:
    network:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: NetworkMap
      name: copy-of-windows-7sj4h
      namespace: konveyor-forklift
    storage:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: StorageMap
      name: copy-of-windows-7tq46
      namespace: konveyor-forklift
  preserveStaticIPs: true
  provider:
    destination:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: dev-kubevirt
      namespace: konveyor-forklift
      uid: 9869803a-4825-49cb-8bee-c0b9ba116030
    source:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: sbx-vc
      namespace: konveyor-forklift
      uid: 8df052e1-31e0-48bc-88c8-1d504e795889
  targetNamespace: forklift-migration
  vms:
  - id: vm-27411
    name: win-nextgen-01
  warm: false
status:
  conditions:
  - category: Required
    lastTransitionTime: "2024-10-18T09:08:36Z"
    message: The migration plan is ready.
    status: "True"
    type: Ready
  migration: {}
  observedGeneration: 2

**Comment by mnecas** [comment]
in your log the indenting broke so it's hard to read please use next time ``` in the start and end 
The `preserveStaticIPs` should go the the 
```
apiVersion: forklift.konveyor.io/v1beta1
kind: Plan
metadata:
annotations:
populatorLabels: "True"
creationTimestamp: "2024-10-18T09:02:46Z"
generation: 2
name: copy-of-windows
namespace: konveyor-forklift
resourceVersion: "617907626"
uid: 5d79ebd5-3bd4-4cd7-ab3b-81f00361c354
spec:
      preserveStaticIPs: true
....
```
but it looks like you put it in the storagemap

**Comment by jsakil14** [comment]
> in your log the indenting broke so it's hard to read please use next time ``` in the start and end The `preserveStaticIPs` should go the the plan spec
> 
> ```
> apiVersion: forklift.konveyor.io/v1beta1
> kind: Plan
> metadata:
> annotations:
> populatorLabels: "True"
> creationTimestamp: "2024-10-18T09:02:46Z"
> generation: 2
> name: copy-of-windows
> namespace: konveyor-forklift
> resourceVersion: "617907626"
> uid: 5d79ebd5-3bd4-4cd7-ab3b-81f00361c354
> spec:
>       preserveStaticIPs: true
> ....
> ```
> 
> but it looks like you put it in the storagemap

My bad - can you refer to this https://github.com/kubev2v/forklift-console-plugin/issues/1133#issuecomment-2421946040

**Comment by mnecas** [comment]
okay looks like forklift was not released with this feature yet... 
proper fix: I need to do the release
WA/hack you can edit the: `kubectl edit crd plans.forklift.konveyor.io` and add there the `preserveStaticIPs`
https://github.com/kubev2v/forklift/blob/9b19cb784326b36f031ac45da4fabba43020c14f/operator/config/crd/bases/forklift.konveyor.io_plans.yaml#L162-L164

**Comment by mnecas** [comment]
Or install it form the latest index
```
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: forklift-konveyor
  namespace: openshift-marketplace
spec:
  displayName: Forklift
  publisher: Konveyor
  sourceType: grpc
  image: quay.io/kubev2v/forklift-operator-index:latest
  updateStrategy:
    registryPoll:
      interval: 10m0s
```

**Comment by cloudcafetech** [comment]
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: konveyor-forklift
  namespace: konveyor-forklift
spec:
  displayName: Forklift Operator
  image: quay.io/kubev2v/forklift-operator-index:release-2.7
  publisher: Konveyor
  sourceType: grpc
```

Right now I am using above catalogsource but Preserve static IPs of Windows VM not working, throwing following error.

```
Danger alert:The plan is not ready - VMMissingGuestIPs
Guest information on vNICs is missing, cannot preserve static IPs. Make sure VMware tools are installed and the VM is running.. To troubleshoot, check the Forklift controller pod logs.
```

If I disable in in plan then Windows VM (in Kubevirt) taking Ip from DHCP.

Source (VMware):

![Image](https://github.com/user-attachments/assets/7bd5465c-55c0-481d-96ba-a99906f5df05)

Destination (Kubevirt):

![Image](https://github.com/user-attachments/assets/58bfbfc2-848d-438d-b9d9-560c7080bc73)

**Comment by cloudcafetech** [comment]
@mnecas 

Getting error from latest image (**quay.io/kubev2v/forklift-operator-index:latest**) 

```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: konveyor-forklift
  namespace: konveyor-forklift
spec:
  displayName: Forklift Operator
  publisher: Konveyor
  sourceType: grpc
  image: quay.io/kubev2v/forklift-operator-index:latest
  #image: quay.io/kubev2v/forklift-operator-index:release-2.7
```

- error log

```
      Reason:      CrashLoopBackOff
    Last State:    Terminated
      Reason:      Error
      Message:     time="2025-03-26T01:30:48Z" level=info msg="starting pprof endpoint" address="localhost:6060"
time="2025-03-26T01:30:48Z" level=info msg="cache directory is empty, using preferred backend" backend=pogreb.v1 cache=/tmp/opm-serve-cache-3170276266 configs=/configs
time="2025-03-26T01:30:48Z" level=info msg="building cache" cache=/tmp/opm-serve-cache-3170276266 configs=/configs
time="2025-03-26T01:30:48Z" level=fatal msg="failed to load or rebuild cache: failed to rebuild cache: build package index: process package \"forklift-operator\": package \"forklift-operator\", bundle \"forklift-operator.v99.0.0\" not found in any channel entries"
```

but release-2.7 no issue except not able to discover Virtual Machine & Host getting error **(Inventory server is not reachable. To troubleshoot, check the Forklift controller pod logs.**)

![Image](https://github.com/user-attachments/assets/b0502dea-81e3-4b10-b9b0-5fade2217aec)
