### ISSUE TITLE
forklift deployment in dark / DMZ clusters

### ISSUE THREAD

**Issue by jsakil14** [kubev2v/forklift#1173]
I am looking for options to deploy forklift on kubevirt cluster which is running in DMZ zone without access to quay.io repo. Can we build the images to local artifactory? any reference to doc will be helpful.

**Comment by jing2uo** [comment]
I'm not sure if you still need this reply at this point. In my recent attempts, I referred to the instructions in [kubev2v/forklift/release-2.7 README](https://github.com/kubev2v/forklift/blob/release-2.7/README.md). You can also use skopeo to sync images from Quay to your own private registry. Once the image is available in your private registry, you can create a subscription (subs) and inject the image name as an environment variable via config: env. After that, it should work as expected.

Let me know if you need further assistance!

**Comment by jing2uo** [comment]
Here’s an example Subscription YAML that demonstrates how to configure the forklift-operator with custom image names injected via environment variables. This aligns with the approach I mentioned earlier (syncing images to a private registry and specifying them in the config: env section). Below is the sample configuration:

```yaml

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    cpaas.io/target-namespaces: ""
  finalizers:
    - cpaas.io/olm-finalizer
  labels:
    catalog: system
    operators.coreos.com/forklift-operator.konveyor-forklift: ""
  name: forklift-operator
  namespace: konveyor-forklift
spec:
  channel: development
  config:
    env:
      - name: API_IMAGE
        value: registry.example.com/3rdparty/kubev2v/forklift-api:latest
      - name: MUST_GATHER_IMAGE
        value: registry.example.com/3rdparty/kubev2v/forklift-must-gather:latest
      - name: UI_PLUGIN_IMAGE
        value: registry.example.com/3rdparty/kubev2v/forklift-console-plugin:latest
      - name: VALIDATION_IMAGE
        value: registry.example.com/3rdparty/kubev2v/forklift-validation:latest
      - name: VIRT_V2V_IMAGE
        value: registry.example.com/3rdparty/kubev2v/forklift-virt-v2v:latest
      - name: POPULATOR_CONTROLLER_IMAGE
        value: registry.example.com/3rdparty/kubev2v/populator-controller:latest
      - name: OVIRT_POPULATOR_IMAGE
        value: registry.example.com/3rdparty/kubev2v/ovirt-populator:latest
      - name: OPENSTACK_POPULATOR_IMAGE
        value: registry.example.com/3rdparty/kubev2v/openstack-populator:latest
      - name: OVA_PROVIDER_SERVER_IMAGE
        value: registry.example.com/3rdparty/kubev2v/forklift-ova-provider-server:latest
  installPlanApproval: Automatic
  name: forklift-operator
  source: konveyor-forklift
  sourceNamespace: cpaas-system
```
