### ISSUE TITLE
Reconcile fails with invalid resource name (/)

### ISSUE THREAD

**Issue by kaplan-michael** [kubev2v/forklift#878]
I have two clusters, one is OCP 4.14 and one is OKD 4.15
I have installed forklift on the OKD cluster, setup a provider and went to try to create a migration plan. after creation. it will never populate the status field and in forklift controller logs I get this
```bash
{"level":"error","ts":"2024-05-02 01:33:43.719","logger":"plan|tdw65","msg":"Reconcile failed.","plan":{"name":"sno-fcf70ae8","namespace":"konveyor-forklift"},"error":"VM not found. caused by: 'invalid resource name \"vms/fedora-tmp\": [may not contain '/']'","stacktrace":"github.com/konveyor/forklift-controller/pkg/controller/base.(*Reconciler).Ended\n\tpkg/controller/base/controller.go:57\ngithub.com/konveyor/forklift-controller/pkg/controller/plan.Reconciler.Reconcile.func1\n\tpkg/controller/plan/controller.go:170\ngithub.com/konveyor/forklift-controller/pkg/controller/plan.Reconciler.Reconcile\n\tpkg/controller/plan/controller.go:212\ngithub.com/konveyor/forklift-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119\ngithub.com/konveyor/forklift-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tvendor/sigs.k8s.io/controlle...
```

The yaml that I use it this The source and target namespace is `vms`
```
apiVersion: forklift.konveyor.io/v1beta1
kind: Plan
metadata:
  annotations:
    populatorLabels: 'True'
  name: sno-879be8ba
  namespace: konveyor-forklift
spec:
  map:
    network:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: NetworkMap
      name: sno-422411b5
      namespace: konveyor-forklift
      uid: 1ccd885a-8de8-40bd-a921-57f4a0067150
    storage:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: StorageMap
      name: sno-e726041c
      namespace: konveyor-forklift
      uid: bacf6c84-88ba-431e-a765-fcaea9d8f85f
  provider:
    destination:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: host
      namespace: konveyor-forklift
      uid: 0b99af81-c7ad-41a6-acb8-6d79f663388d
    source:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: sno
      namespace: konveyor-forklift
      uid: 41b9ebf3-5d30-42cd-bcb3-44d48db41532
  targetNamespace: vms
  vms:
    - id: b38aae10-126c-4989-951a-12605a8f3a5a
      name: fedora-tmp
```
Am I doing something wrong, or is it a bug?

**Comment by bennyz** [comment]
Does it work with a different namespace?

**Comment by kaplan-michael** [comment]
> Does it work with a different namespace?
Do you mean different source namespace? I don't have a good way to test that now. as I only have VMs in the vms NS.
the destination namespace doesn't seem to matter, it behaves the same no matter which namespace I put there.

**Comment by bennyz** [comment]
> > Does it work with a different namespace?
> 
> Do you mean different source namespace? I don't have a good way to test that now. as I only have VMs in the vms NS. the destination namespace doesn't seem to matter, it behaves the same no matter which namespace I put there.

I had a different issue in mind, but now I've looked at your Plan definition again, and it's missing the namespace, it should look like:
```yaml
  vms:
    - id: 8df8ab48-8969-45df-a330-1b33fc02ee97
      name: ab
      namespace: benny
```

(the id is not actually needed, but the UI adds it)

**Comment by kaplan-michael** [comment]
Hey, 
yeah, that solved it, I had to also fixup the yaml for the storage mapping. 
Thanks for pointing me on the right track that the yaml generated by the UI might be wrong.
I initially generated it with the UI and assumed it would be right for a starting point.

**Comment by bennyz** [comment]
> Hey, yeah, that solved it, I had to also fixup the yaml for the storage mapping. Thanks for pointing me on the right track that the yaml generated by the UI might be wrong. I initially generated it with the UI and assumed it would be right for a starting point.

It should definitely be correct when generated by the UI, which version are you using?

**Comment by kaplan-michael** [comment]
OK, let's reopen this then. the namespace wasn't added, and for storage it used some id for the storageclass in the remote cluster(when I deleted the ID, and added a proper name, it went fine after that) 

I think it is 2.6.0 provided by Konveyor. channel development from your catalog source.
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
  name: konveyor-forklift
  namespace: openshift-marketplace
spec:
  displayName: Forklift Operator
  image: quay.io/kubev2v/forklift-operator-index:latest
  publisher: Konveyor
  sourceType: grpc
```
