### ISSUE TITLE
How to define tolerations and nodeSelector when executing the migration plan?

### ISSUE THREAD

**Issue by jcorreajr** [kubev2v/forklift#909]
Is it possible to define new "tolerations" and "nodeSelectors" for the POD that is created during the execution of the migration plan?

During the execution of the migration plan, a POD running the image: mtv-virt-v2v is created to copy the data.
This POD is initialized with the following "tolerations" and "nodeSelector" settings

```yaml
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300

  nodeSelector:
    kubevirt.io/schedulable: "true"
```
As we use separate "nodes" to run virtual machines, with specific taints, I need to include these taints within the tolerances session of the created PODs.
Is it possible to do that?
